RMI-PACTA/pacta.executive.summary

- R/prep_data_executive_summary.R
- R/prep_fossil_bars.R
closes ADO https://dev.azure.com/2DegreesInvesting/2DegreesInvesting/_workitems/edit/5815
**This PR:**
- standardises the values for `entity`, `entity_type` and `entity_name`
- all the above are set in the initial `prep_data_executive_summary()` function
- special cases/mappings are removed for consistency throughout the package
> Disentangle entity

- R/render_executive_summary.R
- man/render_executive_summary.Rd
supercedes #68 
fully, properly documents `render_executive_summary()`
> document `render_executive_summary()`

- R/plot_alignment_table.R
- R/plot_fossil_bars.R
- R/plot_scores.R
- R/plot_scores_scorecard.R
- R/prep_alignment_table.R
- R/prep_climate_strategy_scorecard.R
- R/prep_exposures_scorecard.R
- R/prep_exposures_survey.R
- R/prep_fossil_bars.R
- R/prep_green_brown_bars.R
- R/prep_net_zero_commitments.R
- R/prep_scatter.R
- R/prep_scores.R
Follows the current canonical method of avoiding R CMD check notes caused by data masking in {tidyselect} functions.
> Avoid R CMD check notes about {tidyselect} variables

- R/prep_net_zero_commitments.R
closes #76 
I made a mistake while doing the {tidyselect}/data-masking cleanup and used the {tidyselect}-in-quotations style in a `dplyr::distinct()` command, whereas I should have used the `.data$` pronoun style
> use `.data$` pronoun in `dplyr::distinct()`

- R/prep_data_executive_summary.R
keep only the emissions data for the indices that are supposed to be shown in the executive summary
> keep only the required benchmark in indices emissions

- R/prep_alignment_table.R
- R/prep_scatter.R
- R/prep_scores.R
@MonikaFu I think this follows the pre-existing strategy? and it avoids build notes about the datasets not being available (because they're "lazily" loaded?)
> use the `use_toy_data()` util function to load toy datasets

- R/plot_scatter.R
- inst/extdata/PA2022CH_en_exec_summary/template.Rmd
In this PR I remove the `scale_colour_2dii()` calls from scatterplot and use `scale_colour_manual` instead. I also relax the condition for plotting scatter in the template so that 'No data' message is returned if an empty data frame was returned from `prep_data_scatter()`.
> Remove scale colour 2dii

- R/render_executive_summary.R
- R/utils.R
- inst/extdata/PA2022CH_en_exec_summary/template.Rmd
- man/render_executive_summary.Rd
closes #121 
relates to https://github.com/RMI-PACTA/workflow.transition.monitor/pull/78
- handles plot errors
- returns empty plot with text
- writes error message to log file
- corrects output structure in scorecard section
- fixes mistake in cat() in scorecard
- adds link to annex that was missing
- reactivates some functional code bits
> Handle plot errors in rmd

- R/prep_alignment_table.R
- R/prep_scatter.R
- R/prep_scores.R
Since `use_toy_data()` automatically triggers a warning message, using this function as a utility will clutter the console with unnecessary warnings. 
Reverts RMI-PACTA/pacta.executive.summary#117
> Revert "use the `use_toy_data()` util function to load toy datasets"

- R/prep_green_brown_bars.R
BEFORE, where exposures were divided by full size of portfolio (since using `plan_tech_carsten`):
NOW, carsten values are renormalized to sector value (effectively only considering sector exposure):
> `prep_scatter` now considers sector-wise exposure (rather than full portfolio exposure)

- R/prep_green_brown_bars.R
- R/prep_scatter.R
this #166 interfered with the green_brown exposure plot which now always threw errors. It still expected 
so I extracted the change of the above fix into a new function that is specifically used for the scatter plot and not for the green brown bars.
The one used for green brown bars is reverted, everything working again
> sepearte exposure functions for separate plots

- inst/extdata/PA2022CH_en_exec_summary/real-estate-chapter.Rmd
when a user has real estate data only in direct real estate OR in mortgages, some plots cannot be shown. This needs to be handled and a placeholder must be returned rather than having the whole chapter fail
new output:
> Handle re plot errors

- inst/extdata/PA2022CH_en_exec_summary/real-estate-chapter.Rmd
**expectation**
the executive summary part of the real estate `data.json` should have entries for en, de and fr for both direct real estate and mortgages. When an asset type is missing for a user, the values should be NULL for all three languages (but the keys should still exist)
**situation**
If a user has language == EN, there may be missing data paths in the RE `data.json` file, if the user has no data for mortgages
in all such cases, NULL values for DR and FR still exist
**suggested solution**
to avoid failure, we change language to DE temporarily in the RE section, since the DE and EN versions use the exact same graphs anyway
**more context on the situation**
well behaved missing data
badly behaved missing data
> use de language in real estate when language setting is EN

- inst/extdata/PA2022CH_de_exec_summary/scorecard.Rmd
- inst/extdata/PA2022CH_en_exec_summary/scorecard.Rmd
- inst/extdata/PA2022CH_fr_exec_summary/scorecard.Rmd
if real estate data cannot be found for a user, the blocks using the reaL_estate in text retrun NULL rather than erroring out
> handle missing real estate data in score card

- R/prep_exposures_scorecard.R
- R/prep_exposures_survey.R
when changing the mapper a while back, we missed updating `"oil and gas"` to `"oil_and_gas"`. Now fixed, the sector is showing in the ES
> fix exposure plot in scorecard

- inst/extdata/PA2022CH_de_exec_summary/preamble.tex
- inst/extdata/PA2022CH_fr_exec_summary/preamble.tex
The files `preamble.tex` seem to have fallen out of sync. `hyperref` package was missing from DE and FR
> Align `preambles.tex` across EN, FR and DE

- DESCRIPTION
remove {gridExtra} dependency, which is no longer needed after #175
> remove {gridExtra} dependency, which is no longer needed after #175

- .Rbuildignore
- .github/workflows/pkgdown.yaml
- .gitignore
- DESCRIPTION
- _pkgdown.yml
- man/pacta.executive.summary-package.Rd
Since this repo is public, and it's a legit R package, might as well have a {pkgdown} site.
> add a {pkgdown} site

- inst/extdata/PA2022CH_de_exec_summary/scorecard.Rmd
- inst/extdata/PA2022CH_en_exec_summary/scorecard.Rmd
- inst/extdata/PA2022CH_fr_exec_summary/scorecard.Rmd
closes ADO 5887: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/5887?src=WorkItemMention&src-action=artifact_link
This PR:
- fixes the column type of the climate initiative indicator when reading in pre-generated user results
- it was falsely set to numeric and should be logical
- the numeric type lead to TRUE values turning into NAs, which means that members of initiatives will falsely see  a "NO" value, for their overall survey replies to the relevant question in the climate score card
> fix column type

- R/prep_alignment_table.R
Since the `scenario_thresholds` file now has multiple possible `scenario_source`'s, it is important to quickly filter it for only the relevant source, otherwise strange bugs appear:
> feat: immediately filter for relevant `scenario_source`

- inst/extdata/PA2024CH_en_exec_summary/scorecard.Rmd
- inst/extdata/PA2024CH_fr_exec_summary/scorecard.Rmd
I somehow missed adding the parameters to these two functions in #314
> fix: `prep_scorecard` template gains missing parameters

- inst/extdata/PA2024CH_de_exec_summary/survey-chapter.Rmd
- inst/extdata/PA2024CH_en_exec_summary/survey-chapter.Rmd
- inst/extdata/PA2024CH_fr_exec_summary/survey-chapter.Rmd
In this PR I change the names of some plots to use the survey engagement plots with peer info as requested by FOEN. These changes will work if we are using the newest version of `user_data` as in this branch: https://github.com/RMI-PACTA/user_results/pull/24#issuecomment-2168243501
@AlexAxthelm can you help me set up testing to make sure this change works as intended?
> Use plots with peer info for engagement

- DESCRIPTION
- R/render_executive_summary.R
- inst/extdata/PA2024CH_de_exec_summary/scorecard.Rmd
- inst/extdata/PA2024CH_de_exec_summary/template.Rmd
- inst/extdata/PA2024CH_en_exec_summary/scorecard.Rmd
- inst/extdata/PA2024CH_en_exec_summary/template.Rmd
- inst/extdata/PA2024CH_fr_exec_summary/scorecard.Rmd
- inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
- man/render_executive_summary.Rd
This PR builds on code implemented in #340, making it fully functional together with https://github.com/RMI-PACTA/workflow.transition.monitor/pull/331. 
NOTE: Also, for the PR to run without errors the `pacta-data` folder needs to contain `fin_data_net_zero_targets.csv` and has to use the most recent version of the testing user_data (https://github.com/RMI-PACTA/user_results/pull/24/files/f75b9955f640a74124003e524a6a5789d9b616b8..355ef24f21422238c88be9ad6ff571ef2d5e56db).
> Update scorecard to use new SBTi calculations

- inst/extdata/PA2024CH_de_exec_summary/template.Rmd
- inst/extdata/PA2024CH_en_exec_summary/template.Rmd
- inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
I couldn't figure out how to actually convert these into Footnotes, since the first of the footnotes are stemming from content in the text body itself, while the second footnote comes from data that is within a plot (i don't think LaTeX can even pick up notes from that aahah)
In this PR, I've simply tried to make all footnotes the same size. Will test with EN on CI first, and then port changes to other languages if it works.
Maybe closes #251 
Partially addresses https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/12058
> make all footnotes same size

- inst/extdata/PA2024CH_de_exec_summary/template.Rmd
- inst/extdata/PA2024CH_en_exec_summary/template.Rmd
- inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
This plot was exploding off the screen:
Fixed in all languages
> Annex exclusion dart plot doesn't explode across the page

- inst/extdata/PA2024CH_de_exec_summary/template.Rmd
- inst/extdata/PA2024CH_en_exec_summary/template.Rmd
- inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
After adjusting the margins, it was noticed that many plots appeared on their own single page. 
To combine more plots on a single page, we elected to remove several page breaks. 
Supersedes https://github.com/RMI-PACTA/pacta.executive.summary/pull/391
FYI @hodie and @MonikaFu
> remove unnecessary page breaks
