R/prep_scores.R
closes ADO https://dev.azure.com/2DegreesInvesting/2DegreesInvesting/_workitems/edit/5810
This PR updates the thresholds for the aggregate score grades to reflect the final version of the executive summary
fyi @Antoine-Lalechere @Tilmon
=> update agg score rules

template.Rmd
In this PR I change the template code so that it uses the data which are an output of `prep_data_executive_summary()` if those are found in the environemnt. Otherwise, it assigns all datasets to `NULL`. This is the first step to integrating PACTA analysis results in the template.
=> Use data if exist

R/prep_scores.R
closes ADO: https://dev.azure.com/2DegreesInvesting/2DegreesInvesting/_workitems/edit/6005
This PR:
- adds a separate calculation for emission intensity sectors to derive a sector score based on sectoral emission intensities
- follows the formula: (scenario_emission_intensity_t5 - planned_emission_intensity_t5) / scenario_emission_intensity_t5
- combines the sector scores for roadmap and emission intensity sectors and proceeds with the portfolio aggregation as before
fyi @Antoine-Lalechere
=> calculate aggregate score for emission intensity sectors

R/plot_scores_scorecard.R, R/prep_scores_scorecard.R, tests/testthat/_snaps/plot_alignment_table.md
Adopt score plots in scorecard
=> Adopt scores scorecard

R/plot_scores.R, man/plot_scores.Rd
=> plot_score returns aviation, not cement

R/lookup.R
=> adapt lookup index names to prepped indices files

PA2022CH_en_exec_summary/template.Rmd
climat score card: add scenario name and benchmarks as per latest requirements
=> climate scorecard add benchmark and scenario name

PA2022CH_en_exec_summary/template.Rmd, R/prep_data_executive_summary.R, R/render_executive_summary.R
relates to [workflow PR](https://github.com/RMI-PACTA/workflow.transition.monitor/pull/29)
- adds coverage information to ES scorecard section
- this requires passing the audit file
- and passing currency exchange information
- preparation based on the steps used in interactive report
=> Value covered

inst/extdata/PA2022CH_en_exec_summary/template.Rmd
Relates to #74
We know that this diagram will break when run on Docker, so until it is fixed let's remove it from the report so we can get things generating on beta <3
=> Temporarily remove broken diagram

inst/extdata/PA2022CH_en_exec_summary/template.Rmd
adds text for the EN template so that formatting can commence
based on what is currently considered the final version of the ES
=> Text for en template

R/prep_alignment_table.R, inst/extdata/PA2022CH_en_exec_summary/template.Rmd
This PR:
- corrects the technologies shown in the tech alignment table as discussed in the ES workgroup (drop fuelcell, reintroduce oil and gas)
- formats the footnotes
=> Tech alignment page

inst/extdata/PA2022CH_en_exec_summary/template.Rmd
add two footnotes on. the exposure page that I missed before
=> add footnotes that were missed

R/prep_climate_strategy_scorecard.R, R/prep_data_executive_summary.R, R/prep_emissions_scorecard.R, inst/extdata/PA2022CH_en_exec_summary/template.Rmd, man/prep_climate_strategy_scorecard_engagement.Rd, man/prep_climate_strategy_scorecard_initiatives.Rd, man/prep_climate_strategy_scorecard_voting.Rd
depends on https://github.com/RMI-PACTA/user_results/pull/18
This PR:
- fixes remaining issues with the climate score card
- moves bits out of tables into the right sentences
- adds % of emissions covered
- adds remaining explainer pages
=> Remaining pieces scorecard

inst/extdata/PA2022CH_en_exec_summary/template.Rmd
Closes #59 
I can't reproduce the issue that @jacobvjk had with the portfolio provided to me by @jdhoffa. Happy to test with other datasets before we merge this in but in principle the scatterplot works for me.
=> Bring back scatterplot

R/prep_climate_strategy_scorecard.R, R/prep_emissions_scorecard.R
depends on #96... sort of, to pass tests anyway
=> avoid "no visible global variable" notes

R/prep_diagram.R
closes ADO 5595: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/5595
show 0 values in flow chart if one of the asset types is missing in the portfolio
=> clean up and fix filter

inst/extdata/PA2022CH_en_exec_summary/survey-chapter.Rmd, inst/extdata/PA2022CH_en_exec_summary/template.Rmd
- this includes the final text for the EN template
- adds the relevant text pieces for RE
- adds the number of peers in the given user's group
=> update en template to final version

.gitignore, pacta.executive.summary.Rproj
e.g. https://github.com/RMI-PACTA/pacta.portfolio.analysis/blob/main/pacta.portfolio.analysis.Rproj
=> include Rproj and align with other repos

R/prep_data_executive_summary.R, R/prep_fossil_bars.R
=> Filter indices in main prep

R/plot_scatter.R
This should fix the weird error we've been getting with scatter plots, though the colours will now be ugly. 
Followed up in #109
=> disable scale_colour_2dii

inst/extdata/PA2022CH_en_exec_summary/template.Rmd
Reverts RMI-PACTA/pacta.executive.summary#126
=> Revert "fix typo"

inst/extdata/PA2022CH_en_exec_summary/survey-chapter-alternate.Rmd, inst/extdata/PA2022CH_en_exec_summary/template.Rmd
closes #125 
adds placeholder for survey section when no survey data can be found
=> add placeholder page in case no survey data found

inst/extdata/PA2022CH_en_exec_summary/real-estate-chapter.Rmd, inst/extdata/PA2022CH_en_exec_summary/template.Rmd
=> Small cleanup

R/prep_diagram.R, R/prep_emissions_scorecard.R
=> Correct emissions scorecard

R/plot_scores_scorecard.R
In this PR I modify scores scorecard plot so that it returns only plots for assets in the data.
=> Dont facet over assets if not in data

R/plot_fossil_bars.R, R/plot_green_brown_bars.R, inst/extdata/PA2022CH_en_exec_summary/template.Rmd
Given the new layout, more plot tinkering is needed.
=> Adjust sizes ES round 2

R/plot_emissions_scorecard.R, R/plot_exposures_scorecard.R, R/plot_scores_scorecard.R, inst/extdata/PA2022CH_en_exec_summary/template.Rmd
Adjust sizes in chart to recent layout.
=> Further size adjustments

inst/extdata/PA2022CH_en_exec_summary/template.Rmd
adds footnote
BUT text does not fit on page anymore. I am a bit concerned how it can fit in other languages...
trying to fit it all on the same page, but maybe you know how to do this quicker @AlexAxthelm
=> add footnote for scenario choice

R/utils-re-exports.R, inst/extdata/PA2022CH_en_exec_summary/survey-chapter.Rmd
Closes #143 
Increased size slightly for the first two rows and improved the exclusion charts layout (not so tall anymore).
=> Adjust sizes survey

R/plot_emissions_scorecard.R, inst/extdata/PA2022CH_en_exec_summary/template.Rmd
=> Update labels emissions scaorecard

inst/extdata/PA2022CH_en_exec_summary/template.Rmd, pacta.executive.summary.Rproj
relates to https://github.com/RMI-PACTA/workflow.transition.monitor/pull/92
=> switch back to xelatex

inst/extdata/PA2022CH_de_exec_summary/template.Rmd, inst/extdata/PA2022CH_en_exec_summary/template.Rmd, inst/extdata/PA2022CH_fr_exec_summary/template.Rmd
=> Fix exposures footnote

inst/extdata/PA2022CH_de_exec_summary/scorecard.Rmd, inst/extdata/PA2022CH_de_exec_summary/template.Rmd
closes #221 
closes #222 
and I overruled one choice of words because I can (does not change the meaning, just sounds better)
=> Fix wording de

inst/extdata/PA2022CH_de_exec_summary/template.Rmd, inst/extdata/PA2022CH_en_exec_summary/template.Rmd, inst/extdata/PA2022CH_fr_exec_summary/template.Rmd
=> Remove industry type from annex text

inst/extdata/PA2022CH_en_exec_summary/template.Rmd, inst/extdata/PA2022CH_fr_exec_summary/template.Rmd
closes #203 
German template already adjusted in prior PR
=> more specifc description of pacta coverage

inst/extdata/PA2022CH_en_exec_summary/scorecard.Rmd
It seems that the headers have already been capitalized in DE and FR. 
Closes #237
=> Capitalize headers

inst/extdata/PA2022CH_de_exec_summary/scorecard.Rmd, inst/extdata/PA2022CH_en_exec_summary/scorecard.Rmd, inst/extdata/PA2022CH_fr_exec_summary/scorecard.Rmd
This was supposed to have been handled in #233 but somehow i didn't push the last commit:
=> final fixing of degrees

R/plot_scores.R
=> Add C to legend

inst/extdata/PA2022CH_de_exec_summary/template.Rmd, inst/extdata/PA2022CH_en_exec_summary/template.Rmd, inst/extdata/PA2022CH_fr_exec_summary/template.Rmd
=> Add vertical spacing before logo texts

R/plot_fossil_bars.R
=> Change how index name is formatted

README.md
=> manually render README since CI render fails

.github/workflows/add-prs-and-issues-to-project.yml
will auto add new issues and PRs to the [Transition Monitor project](https://github.com/orgs/RMI-PACTA/projects/8/)
=> add an action to add new issues and PRs to project

.github/workflows/render-readme.yml
=> Change to use GITHUB_TOKEN

DESCRIPTION, NEWS.md
I tried my best to review the git history here and generate good `NEWS.md` comments for each public-facing change, but I don't have the most visibility on what goes on in this package. 
@cjyetman @jacobvjk @MonikaFu please feel free to comment
=> Increment version number to 0.1.0

DESCRIPTION, NEWS.md
- Increment version number to 0.1.1
- update NEWS.md
=> release 0.1.1

inst/extdata/PA2024CH_de_exec_summary/scorecard.Rmd, inst/extdata/PA2024CH_fr_exec_summary/scorecard.Rmd
Just to make sure that no template in the PA2024CH is trying to use old `user_results`.
=> Copy new scorecard sections from en to fr and de (untranslated)

R/prep_exposures_scorecard.R, R/prep_fossil_bars.R, R/prep_green_brown_bars.R, R/prep_scatter.R, R/render_executive_summary.R, data-raw/scenario_thresholds.R, man/prep_exposures_scorecard.Rd, man/prep_fossil_bars.Rd, man/prep_green_brown_bars.Rd, man/prep_scatter.Rd, man/render_executive_summary.Rd
Relates to https://github.com/RMI-PACTA/workflow.transition.monitor/pull/315#discussion_r1624585303
=> bug: rename NZE to NZE_2050

inst/extdata/PA2024CH_en_exec_summary/scorecard.Rmd, inst/extdata/PA2024CH_en_exec_summary/template.Rmd
Updating the text of ES to reflect COP 2024.
Testing here: https://github.com/RMI-PACTA/workflow.transition.monitor/pull/353
=> Update text ES

inst/extdata/PA2024CH_de_exec_summary/scorecard.Rmd, inst/extdata/PA2024CH_de_exec_summary/template.Rmd, inst/extdata/PA2024CH_en_exec_summary/scorecard.Rmd, inst/extdata/PA2024CH_en_exec_summary/template.Rmd
Updating to make it easier to translate.
=> Update for translations

inst/extdata/PA2024CH_de_exec_summary/template.Rmd
Incorporating translations made by @MKensbock 
@jdhoffa FYI
=> Translate template.Rmd into German.

inst/extdata/PA2024CH_de_exec_summary/scorecard.Rmd
Here I implement translations done by @MKensbock.
Relates to #358
=> Translate scorecard

inst/extdata/PA2024CH_en_exec_summary/template.Rmd
ADO: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_sprints/taskboard/P4I/2DegreesInvesting/2024_20?workitem=11781
=> Fix annex titles

inst/extdata/PA2024CH_en_exec_summary/scorecard.Rmd, inst/extdata/PA2024CH_en_exec_summary/template.Rmd
ADO: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_sprints/taskboard/P4I/2DegreesInvesting/2024_20?workitem=11781
=> Remove 'UPDATED' comments helpful for translations

inst/extdata/PA2024CH_en_exec_summary/template.Rmd
=> Fix typos in PA2024CH EN template

inst/extdata/PA2024CH_de_exec_summary/scorecard.Rmd
Typo was introduced in #367
(I don't think anyone committed my suggestion :-D )
=> fix `"eicht` typo

inst/extdata/PA2024CH_de_exec_summary/template.Rmd, inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
Note: This was already completed for EN.
Closes https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/12053
=> all reference to wuest become fahrlander

inst/extdata/PA2024CH_fr_exec_summary/survey-chapter.Rmd
The character used was incorrect. 
Closes https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/12052
=> Use correct apostraphe

inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
French version of https://github.com/RMI-PACTA/pacta.executive.summary/pull/380
=> Update FR template.Rmd for full width

inst/extdata/PA2024CH_en_exec_summary/template.Rmd
EN version of https://github.com/RMI-PACTA/pacta.executive.summary/pull/380
=> Update EN template.Rmd for full width

inst/extdata/PA2024CH_fr_exec_summary/preamble.tex
@jdhoffa FR margin changes in preamble.tex
=> Update preamble.tex in FR

inst/extdata/PA2024CH_en_exec_summary/preamble.tex
@jdhoffa EN version of margin changes.
=> Update preamble.tex in EN

inst/extdata/PA2024CH_de_exec_summary/template.Rmd, inst/extdata/PA2024CH_en_exec_summary/template.Rmd, inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
@jdhoffa @MonikaFu I don't know how to combine multiple files into one commit, so just German here
=> Update template.Rmd to have content full width

inst/extdata/PA2024CH_de_exec_summary/preamble.tex, inst/extdata/PA2024CH_en_exec_summary/preamble.tex, inst/extdata/PA2024CH_fr_exec_summary/preamble.tex
Changing the esbox to have a bit more padding and align properly on the right.
=> Don't Merge - Update preamble.tex margins

inst/extdata/PA2024CH_de_exec_summary/template.Rmd
This link was already updated in https://github.com/RMI-PACTA/pacta.executive.summary/pull/372
=> Tech Debt: Remove completed "TODO"

R/prep_data_executive_summary.R
"MSCI World" -> "MSCI - WORLD"
=> Update index name change

R/plot_green_brown_bars.R, R/prep_data_executive_summary.R, R/prep_green_brown_bars.R, R/prep_scatter.R, R/prep_scores.R
Closes #387
Removed TODOs that are not relevant anymore. Turned two into issues: #393 and #392 .
=> Remove TODOs
